<a href="https://colab.research.google.com/github/dhivyapm/GRA/blob/main/KNN_aspect.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
df = pd.read_csv('https://raw.githubusercontent.com/dhivyapm/GRA/main/aspect_AAjN_emotion.csv',sep=',')

In [ ]:
df['emotions'] = df['emotions'].fillna('unknown')

In [ ]:
y = pd.DataFrame(df['emotions'])

In [ ]:
enc = LabelEncoder()
emotions = enc.fit_transform(y)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
emotions

array([5, 5, 2, ..., 1, 5, 5])

In [ ]:
in_emotions = enc.inverse_transform(emotions)

In [ ]:
in_emotions

array(['unknown', 'unknown', 'Happy', ..., 'Fear', 'unknown', 'unknown'],
      dtype=object)

In [ ]:
X = df.iloc[:,1].values
y = emotions

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import KNeighborsClassifier
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.15, random_state = 1)
vect = CountVectorizer()
vect.fit(X_train)
X_train = vect.transform(X_train)
X_test = vect.transform(X_test)

In [ ]:
X_t = vect.transform(X)

In [ ]:
#using Sklearn library
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
k_range = range(1, 10)

# We can create Python dictionary using [] or dict()
scores = []

# We use a loop through the range 1 to 21
# We append the scores in the dictionary
knn = KNeighborsClassifier(n_neighbors=5, p=1, metric = 'euclidean')
knn.fit(X_train, y_train)
ne = knn.kneighbors(X_t[48], 5, return_distance =True)
y_pred = knn.predict(X_t[48])
#scores = metrics.accuracy_score(y_train[48], y_pred)
print(ne)
#print(scores)
#print(y_pred)

(array([[0.        , 1.41421356, 1.73205081, 1.73205081, 2.        ]]), array([[ 8656,  1828, 11566, 15062, 11235]]))


In [ ]:
vect.inverse_transform(X_t[48])

[array(['absolutely', 'beautiful', 'mountain'], dtype='<U22')]

In [ ]:
enc.inverse_transform(y_pred)

array(['Happy'], dtype=object)

In [ ]:
#using Sklearn library
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
k_range = range(1, 10)

# We can create Python dictionary using [] or dict()
scores = []

# We use a loop through the range 1 to 21
# We append the scores in the dictionary
knn = KNeighborsClassifier(n_neighbors=5, p=1, metric = 'euclidean')
knn.fit(X_train, y_train)
ne = knn.kneighbors(X_t[3159], 5, return_distance =True)
y_pred1 = knn.predict(X_t[3159])
#scores = metrics.accuracy_score(y_train[48], y_pred)
print(ne)
#print(scores)
#print(y_pred)

(array([[0.        , 1.41421356, 1.41421356, 1.41421356, 1.41421356]]), array([[14182, 12116, 10303,  2886, 11600]]))


In [ ]:
vect.inverse_transform(X_t[3159])

[array(['movie', 'pretty', 'unacceptable'], dtype='<U22')]

In [ ]:
enc.inverse_transform(y_pred1)

array(['Happy'], dtype=object)

In [ ]:
#using Sklearn library
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
k_range = range(1, 10)

# We can create Python dictionary using [] or dict()
scores = []

# We use a loop through the range 1 to 21
# We append the scores in the dictionary
knn = KNeighborsClassifier(n_neighbors=5, p=1, metric = 'euclidean')
knn.fit(X_train, y_train)
ne = knn.kneighbors(X_t[741], 5, return_distance =True)
y_pred1 = knn.predict(X_t[741])
#scores = metrics.accuracy_score(y_train[48], y_pred)
print(ne)
#print(scores)
#print(y_pred)

(array([[1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356]]), array([[15323,   621,  9852, 14140, 11340]]))


In [ ]:
vect.inverse_transform(X_t[741])

[array(['bad', 'movie', 'really'], dtype='<U22')]

In [ ]:
enc.inverse_transform(y_pred1)

array(['Surprise'], dtype=object)

In [ ]:
#using Sklearn library
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
k_range = range(1, 10)

# We can create Python dictionary using [] or dict()
scores = []

# We use a loop through the range 1 to 21
# We append the scores in the dictionary
knn = KNeighborsClassifier(n_neighbors=5, p=1, metric = 'euclidean')
knn.fit(X_train, y_train)
ne = knn.kneighbors(X_t[3114], 5, return_distance =True)
y_pred1 = knn.predict(X_t[3114])
#scores = metrics.accuracy_score(y_train[48], y_pred)
print(ne)
#print(scores)
#print(y_pred)

(array([[0.        , 1.41421356, 1.41421356, 1.41421356, 1.41421356]]), array([[15896, 13496, 15378, 15434,  3561]]))


In [ ]:
vect.inverse_transform(X_t[3114])

[array(['good', 'job', 'pretty'], dtype='<U22')]

In [ ]:
enc.inverse_transform(y_pred1)

array(['Happy'], dtype=object)

In [ ]:
#using Sklearn library
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
k_range = range(1, 10)

# We can create Python dictionary using [] or dict()
scores = []

# We use a loop through the range 1 to 21
# We append the scores in the dictionary
knn = KNeighborsClassifier(n_neighbors=5, p=1, metric = 'euclidean')
knn.fit(X_train, y_train)
ne = knn.kneighbors(X_t[294], 5, return_distance =True)
y_pred1 = knn.predict(X_t[294])
#scores = metrics.accuracy_score(y_train[48], y_pred)
print(ne)
#print(scores)
#print(y_pred)

(array([[0.        , 1.41421356, 1.41421356, 1.41421356, 1.41421356]]), array([[2886, 6631, 8651, 6450, 9391]]))


In [ ]:
vect.inverse_transform(X_t[294])

[array(['good', 'movie', 'pretty'], dtype='<U22')]

In [ ]:
enc.inverse_transform(y_pred1)

array(['Happy'], dtype=object)

In [ ]:
#using Sklearn library
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
k_range = range(1, 10)

# We can create Python dictionary using [] or dict()
scores = []

# We use a loop through the range 1 to 21
# We append the scores in the dictionary
knn = KNeighborsClassifier(n_neighbors=5, p=1, metric = 'euclidean')
knn.fit(X_train, y_train)
ne = knn.kneighbors(X_t[5522], 5, return_distance =True)
y_pred1 = knn.predict(X_t[5522])
#scores = metrics.accuracy_score(y_train[48], y_pred)
print(ne)
#print(scores)
#print(y_pred)

(array([[0.        , 1.41421356, 1.41421356, 1.41421356, 1.41421356]]), array([[10828,  3087, 13219, 13210,  7135]]))


In [ ]:
vect.inverse_transform(X_t[5522])

[array(['time', 'well', 'worth'], dtype='<U22')]

In [ ]:
enc.inverse_transform(y_pred1)

array(['Fear'], dtype=object)

In [ ]:
#using Sklearn library
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
k_range = range(1, 10)

# We can create Python dictionary using [] or dict()
scores = []

# We use a loop through the range 1 to 21
# We append the scores in the dictionary
knn = KNeighborsClassifier(n_neighbors=5, p=1, metric = 'euclidean')
knn.fit(X_train, y_train)
ne = knn.kneighbors(X_t[15522], 5, return_distance =True)

#scores = metrics.accuracy_score(y_train[48], y_pred)
print(ne)
#print(scores)
#print(y_pred)

(array([[1.41421356, 1.41421356, 1.41421356, 1.73205081, 2.        ]]), array([[ 3175,  1753,  8176, 11748, 11619]]))


In [ ]:
y_pred1 = knn.predict(X_t[15522])

In [ ]:
vect.inverse_transform(X_t[15522])

[array(['charm', 'far', 'ha'], dtype='<U22')]

In [ ]:
enc.inverse_transform(y_pred1)

array(['Fear'], dtype=object)

In [ ]:
#using Sklearn library
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
k_range = range(1, 10)

# We can create Python dictionary using [] or dict()
scores = []

# We use a loop through the range 1 to 21
# We append the scores in the dictionary
knn = KNeighborsClassifier(n_neighbors=5, p=1, metric = 'euclidean')
knn.fit(X_train, y_train)
ne = knn.kneighbors(X_t[3182], 5, return_distance =True)

#scores = metrics.accuracy_score(y_train[48], y_pred)
print(ne)
#print(scores)
#print(y_pred)

(array([[0., 2., 2., 2., 2.]]), array([[ 5589,  2826, 12197, 16126, 13172]]))


In [ ]:
y_pred1 = knn.predict(X_t[3182])

In [ ]:
enc.inverse_transform(y_pred1)

array(['Fear'], dtype=object)